language: python                                                                                                                                                                                                            
python:                                                                                                                                                                                                                             
  - "3.3"
install:
   - pip install matplotlib
script:
  - python CurveFitter.py
